apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway
  namespace: monitor                # must match Prometheus namespace
  labels:
    release: prometheus        # must match Prometheus label
spec:
  selector:
    matchLabels:
      app: gateway                  # must match your Service labels
  namespaceSelector:
    matchNames:
      - default                     # where your gateway Service actually runs
  endpoints:
    - port: http                    # must match Service port name
      path: /metrics
      interval: 15s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-service-monitor
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-service-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-service-monitor
subjects:
- kind: ServiceAccount
  name: prometheus-kube-prometheus-prometheus
  namespace: monitor